export interface Server {
  Ping: Number;
  Server: {
    ServerIp: String,
    Port: Number,
    PortTimeCritical: Number,
    CurrentSession: Number,
    TimeLeft: Number,
    PlayersOnServer: Number,
    Players: Number[],
    Settings: {
      Thumbnail: String,
      ServerName: String,
      HasPassword: Boolean,
      ExperienceId: Number,
      TrackLayoutId: Number,
      LiveryId: Number[],
      Difficulty: Number,
      MaxNumberOfPlayers: Number,
      FuelUsage: Number,
      TireWear: Number,
      MechanicalDamage: Number,
      FlagRules: Number,
      QualifyDuration: Number,
      RaceDuration: Number,
      CutRules: Number,
      MandatoryPitStop: Boolean,
      DriveAssist: {
        Preset: Number,
        Transmission: Number,
        Esp: Number,
        SteerAssist: Number,
        BrakeAssist: Number,
        TractionControl: Number,
      },
      Id: Number,
      IsRanked: Boolean,
      PracticeDuration: Number,
      QualifyStartMode: Number,
      Race1Duration: Number,
      Race2Duration: Number,
      Race3Duration: Number,
      ReverseGridPlaces: Number,
    },
  };
}
